title: Subhajit Bandyopadhyay
email: subhajitbn.maths@gmail.com
description: PhD in Math | Project Fellow | Network Science & ML
baseurl: "" 
url: "https://subhajitbn.github.io"

# This handles the project pages
collections:
  projects:
    output: true
    permalink: /projects/:path/
  devlog:
    output: true
    permalink: /devlog/:path/

# Markdown engine
markdown: kramdown
highlighter: rouge

# Removes theme overhead
theme: []

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block_code_engines:
      zig: rouge
