title: Subhajit Bandyopadhyay
email: subhajitbn.maths@gmail.com
description: PhD in Math | Project Fellow | Network Science & ML
baseurl: "" 
url: "https://subhajitbn.github.io"

# This handles the project pages
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Markdown engine
markdown: kramdown
highlighter: rouge

# Essential for the "Crisp" look (removes theme overhead)
theme: []

kramdown:
  input: GFM
  syntax_highlighter: rouge
